<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-31T11:25:19 IST" name="Suite" finished-at="2023-03-31T11:25:46 IST" duration-ms="26807">
    <groups>
    </groups>
    <test started-at="2023-03-31T11:25:19 IST" name="FourTest" finished-at="2023-03-31T11:25:41 IST" duration-ms="21821">
      <class name="TestCases.FourTest">
        <test-method signature="title4()[pri:0, instance:TestCases.FourTest@5dafbe45]" started-at="2023-03-31T11:25:19 IST" name="title4" finished-at="2023-03-31T11:25:38 IST" duration-ms="18807" status="FAIL">
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:86)
at org.junit.Assert.assertTrue(Assert.java:41)
at org.junit.Assert.assertTrue(Assert.java:52)
at TestCases.FourTest.title4(FourTest.java:24)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1589)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- title4 -->
        <test-method is-config="true" signature="closingBrowser()[pri:0, instance:TestCases.FourTest@5dafbe45]" started-at="2023-03-31T11:25:38 IST" name="closingBrowser" finished-at="2023-03-31T11:25:41 IST" duration-ms="2273" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closingBrowser -->
      </class> <!-- TestCases.FourTest -->
    </test> <!-- FourTest -->
    <test started-at="2023-03-31T11:25:19 IST" name="TwoTest" finished-at="2023-03-31T11:25:43 IST" duration-ms="24362">
      <class name="TestCases.TwoTest">
        <test-method signature="title2()[pri:0, instance:TestCases.TwoTest@18ece7f4]" started-at="2023-03-31T11:25:19 IST" name="title2" finished-at="2023-03-31T11:25:43 IST" duration-ms="24317" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- title2 -->
      </class> <!-- TestCases.TwoTest -->
    </test> <!-- TwoTest -->
    <test started-at="2023-03-31T11:25:19 IST" name="ThreeTest" finished-at="2023-03-31T11:25:44 IST" duration-ms="25553">
      <class name="TestCases.ThreeTest">
        <test-method signature="title3()[pri:0, instance:TestCases.ThreeTest@4bff7da0]" started-at="2023-03-31T11:25:19 IST" name="title3" finished-at="2023-03-31T11:25:44 IST" duration-ms="25508" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- title3 -->
      </class> <!-- TestCases.ThreeTest -->
    </test> <!-- ThreeTest -->
    <test started-at="2023-03-31T11:25:19 IST" name="LoginTest" finished-at="2023-03-31T11:25:46 IST" duration-ms="26807">
      <class name="TestCases.LoginTest">
        <test-method is-config="true" signature="browserOpening()[pri:0, instance:TestCases.LoginTest@222a59e6]" started-at="2023-03-31T11:25:19 IST" name="browserOpening" finished-at="2023-03-31T11:25:43 IST" duration-ms="23740" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserOpening -->
        <test-method signature="login(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:TestCases.LoginTest@222a59e6]" started-at="2023-03-31T11:25:43 IST" name="login" data-provider="getLoginData" finished-at="2023-03-31T11:25:45 IST" duration-ms="2780" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Admin]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[admin123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[success]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closure()[pri:0, instance:TestCases.LoginTest@222a59e6]" started-at="2023-03-31T11:25:45 IST" name="closure" finished-at="2023-03-31T11:25:46 IST" duration-ms="241" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closure -->
      </class> <!-- TestCases.LoginTest -->
    </test> <!-- LoginTest -->
  </suite> <!-- Suite -->
</testng-results>
